### ISSUE TITLE
Did not get kafka-amqstreams-consumer-scaledobject in step 5

### ISSUE THREAD

**Issue by weinliu** [zroubalik/keda-openshift-examples#1]
In step 5. Deploy ScaledObject to enable Kafka Consumer application autoscaling
After I 
oc apply -f scaledobject.yaml

I can not get 
```
NAME                                     SCALETARGETKIND      SCALETARGETNAME             MIN   MAX   TRIGGERS   AUTHENTICATION   READY   ACTIVE   FALLBACK   AGE
kafka-amqstreams-consumer-scaledobject   apps/v1.Deployment   kafka-amqstreams-consumer   0     5     kafka                       True    False    False      17s
```

In scaledobject.yaml, I can only see `ScaledObject` with a name `example`, was it a correct` scaledobject.yaml` uploaded?

Thanks

**Comment by zroubalik** [comment]
Are you talking about this part?
https://github.com/zroubalik/keda-openshift-examples/tree/main/kafka/amqstreams#5-deploy-scaledobject-to-enable-kafka-consumer-application-autoscaling

I that directory, the scaledobject.yaml has these contents:
https://github.com/zroubalik/keda-openshift-examples/blob/85fd4ad21db44402d1006c6874e3975c5727395d/kafka/amqstreams/scaledobject.yaml#L1-L19

**Comment by weinliu** [comment]
Thanks for checking out!
